# Generated by Django 2.1 on 2019-03-06 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transacaosite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='utilizavel',
            field=models.BooleanField(default=True, verbose_name='Utilizavel'),
        ),
    ]
