# Generated by Django 2.1 on 2019-01-02 23:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transacaosite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='item_pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_pedido', to='transacaosite.Item'),
        ),
    ]
