# Generated by Django 2.1 on 2019-05-05 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apisite', '0001_initial'),
        ('transacaosite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventarioItemGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField(default=0)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_inventario', to='transacaosite.Item')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_inventario', to='apisite.Inventario')),
            ],
            options={
                'verbose_name': 'item do jogo que o usuario tem',
                'verbose_name_plural': 'itens do jogo que o usuario tem',
                'db_table': 'item_usuario',
            },
        ),
        migrations.RemoveField(
            model_name='itemcompra',
            name='id_usuario',
        ),
    ]
