# Generated by Django 2.1 on 2019-01-06 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transacaosite', '0002_auto_20190102_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='codigo_pagseguro',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
