# Generated by Django 2.1 on 2019-05-10 01:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('transacaosite', '0002_auto_20190505_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='transacao',
            name='data_boleto_criado',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='transacao',
            name='expiration_boleto_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
