# Generated by Django 2.1 on 2019-03-08 00:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transacaosite', '0003_auto_20190308_0040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrinho',
            name='transacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_to_transacao', to='transacaosite.Transacao'),
        ),
    ]
