# Generated by Django 2.1 on 2019-05-25 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apisite', '0001_initial'),
        ('transacaosite', '0004_transacao_valor_boleto'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itens', models.CharField(max_length=1500, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_itens', to='apisite.Inventario')),
            ],
            options={
                'db_table': 'save_itens_session',
            },
        ),
    ]
