# Generated by Django 2.1 on 2019-05-25 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transacaosite', '0005_itemsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemsession',
            name='codigo_boleto',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
