# Generated by Django 2.1 on 2018-11-01 01:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apisite', '0002_remove_inventario_moeda'),
    ]

    operations = [
        migrations.CreateModel(
            name='AtualizaMoeda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moeda_atual', models.BigIntegerField(default=0)),
                ('moeda_adicionada_removida', models.BigIntegerField(default=0)),
                ('moeda_total', models.BigIntegerField(default=0)),
            ],
            options={
                'db_table': 'atualizacao_do_jogo',
            },
        ),
        migrations.CreateModel(
            name='Moeda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_moeda', models.CharField(default='Coincoin', max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='NotaFiscalMoeda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_comprado', models.IntegerField()),
                ('data_transact', models.DateTimeField(auto_now=True)),
                ('atualiza_moeda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quantia_moeda', to='apitransact.AtualizaMoeda')),
                ('inventario_compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ultima_compra', to='apisite.Inventario')),
            ],
            options={
                'db_table': 'nota_fiscal',
                'get_latest_by': 'order_date',
            },
        ),
    ]
