# Generated by Django 2.1 on 2019-01-02 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apisite', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.RemoveField(
            model_name='inventario',
            name='moeda',
        ),
    ]
