# Generated by Django 2.1 on 2018-11-01 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apisite', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventario',
            name='moeda',
        ),
    ]
