# Generated by Django 2.1 on 2018-08-25 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apisite', '0002_inventario_moeda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='moeda',
            field=models.IntegerField(default=5),
        ),
    ]
