# Generated by Django 2.1 on 2018-08-25 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apisite', '0004_auto_20180825_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='moeda',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dono_inventario', to='apisite.Profile'),
        ),
    ]
