# Generated by Django 2.1 on 2018-09-09 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apisite', '0005_auto_20180825_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='moeda',
            field=models.IntegerField(default=0),
        ),
    ]
