# Generated by Django 2.1 on 2018-09-16 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apisite', '0006_auto_20180909_1406'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='inventario',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='item',
        ),
        migrations.AlterField(
            model_name='inventario',
            name='moeda',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inventario_usuario', to='apisite.Profile'),
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
